export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';

export const GET_HOTELS_ERROR = 'GET_HOTELS_ERROR';

export const GET_HOTELS_DETAIL_SUCCESS = 'GET_HOTELS_DETAIL_SUCCESS';

export const GET_HOTELS_DETAIL_ERROR = 'GET_HOTELS_DETAIL_ERROR';